server:
  port: 5002

spring:
  config:
    import:
      - optional:file:env/jwt.env[.properties]

  jackson:
    time-zone: Asia/Seoul
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,threaddump
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      http.server.requests: true

jwt:
  client-secret: ${JWT_CLIENT_SECRET}
  token-expire: ${JWT_TOKEN_EXPIRE}
  refresh-token-expire: ${JWT_REFRESH_TOKEN_EXPIRE}
  issuer: ${JWT_ISSUER}
